---
include:
  - project: cpp-core/ci-model
    file:
      - templates/kaniko.yml
      - templates/rules.yml
      - templates/retag_image.yml
      - templates/conan2/conan.yml
      - jobs/versioning.yml
      - jobs/workflow.yml
  - local: .gitlab/common-vars.yml

stages:
  - build
  - release
  - test

.sources:
  cli:
    - .gitlab/common-vars.yml
    - configs/docker/Dockerfile
    - cli/**/*
    - cpp/**/*

get_image_tag:
  stage: .pre
  image: docker-hosted.artifactory.tcsbank.ru/cicd-images/base-noble:latest
  needs: []
  script:
    - REPO_VERSION=$(git describe --dirty --always --tags)
    - echo ${REPO_VERSION} > version.gen.txt
    - IMAGE_TAG=$(cat configs/docker/Dockerfile .gitlab/common-vars.yml version.gen.txt | sha1sum | cut -d ' ' -f 1)
    - echo "IMAGE_TAG=$IMAGE_TAG"
    - echo "IMAGE_TAG=$IMAGE_TAG" > image_tag.env
  artifacts:
    reports:
      dotenv: image_tag.env
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - !reference [.rules, mr]

build cli image:
  stage: build
  extends: .kaniko::build_and_push::cached
  needs:
    - job: get_image_tag
  variables:
    TARGET_IMAGE: ${REGISTRY_IMAGE_NAME}:${IMAGE_TAG}
    DOCKERFILE: configs/docker/Dockerfile
    DOCKER_BUILD_ARGS: >
      --build-arg BASE_IMAGE
      --build-arg BASE_IMAGE_TAG
      --build-arg WORKDIR
      --build-arg IMAGE_TAG
  rules:
    - changes: !reference [.sources, cli]
  retry: 1

release cli image:
  stage: release
  extends: .retag_image
  needs:
    - job: get project version
    - job: get_image_tag
    - job: build cli image
  variables:
    IMAGE_NAME: ${REGISTRY_IMAGE_NAME}:${IMAGE_TAG}
    TARGET_TAG: release-v${PROJECT_VERSION}
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes: !reference [.sources, cli]

test:
  stage: test
  script:
    - echo 'ok'
